# ===============================================================
# Filename: Makefile
# -------------------------------
# Copyright(C),
# Author: zhenquan.qiu
# Version: V1.0.0
# Last modified: 06/11 2017 23:01
# Description:
#
# Change Log:
# NO.	Author		    Date		Modified
# 00	zhenquan.qiu	06/11 2017
# ===============================================================


CFLAGS := -I. -I../install/cunit-code/include
LDFLAGS := -L../install/cunit-code/lib -lcunit

all:
	$(CC) $(CFLAGS) cunit-example.c $(LDFLAGS) -o cunit-example

